# Generated by Django 5.2 on 2025-05-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='raw_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
