# Generated by Django 5.2 on 2025-05-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_repository_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='raw_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
