# Generated by Django 5.2 on 2025-05-04 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_repository_raw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='works',
        ),
        migrations.RemoveField(
            model_name='repositorywork',
            name='commits',
        ),
        migrations.RemoveField(
            model_name='repositorywork',
            name='issues',
        ),
        migrations.AddField(
            model_name='commit',
            name='work',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='api.repositorywork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='work',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.repositorywork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repositorywork',
            name='contributor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='api.contributor'),
            preserve_default=False,
        ),
    ]
